# Generated by Django 5.2.11 on 2026-03-03 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='コースタイトル')),
                ('slug', models.SlugField(verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('thumbnail', models.ImageField(blank=True, upload_to='courses/', verbose_name='サムネイル')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='レッスンタイトル')),
                ('slug', models.SlugField(verbose_name='スラッグ')),
                ('content_type', models.CharField(choices=[('video', '動画'), ('text', 'テキスト'), ('pdf', 'PDF')], default='text', max_length=10, verbose_name='コンテンツタイプ')),
                ('body', models.TextField(blank=True, verbose_name='本文(HTML)')),
                ('video_url', models.URLField(blank=True, verbose_name='動画URL')),
                ('file', models.FileField(blank=True, upload_to='lessons/', verbose_name='ファイル')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開')),
                ('is_preview', models.BooleanField(default=False, verbose_name='プレビュー可能')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='MemberSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='サイト名')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'member_sites',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='有効期限')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='contacts.contact')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='members.course')),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
    ]
