# Generated by Django 5.2.11 on 2026-03-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('true_false', '○×式'), ('single', '択一式'), ('multiple', '複数選択式')], default='single', max_length=20, verbose_name='問題タイプ')),
                ('text', models.TextField(verbose_name='問題文')),
                ('explanation', models.TextField(blank=True, verbose_name='解説')),
                ('points', models.IntegerField(default=1, verbose_name='配点')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'db_table': 'quiz_questions',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite_quiz',
            field=models.ForeignKey(blank=True, help_text='このテストに合格しないとコースにアクセスできません', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_courses', to='members.lesson', verbose_name='前提テスト'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', '動画'), ('text', 'テキスト'), ('pdf', 'PDF'), ('quiz', 'テスト')], default='text', max_length=10, verbose_name='コンテンツタイプ'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='証書タイトル')),
                ('description', models.TextField(blank=True, verbose_name='メッセージ')),
                ('issuer_name', models.CharField(max_length=200, verbose_name='発行者名')),
                ('template_image', models.ImageField(blank=True, upload_to='certificates/', verbose_name='背景画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='members.course')),
            ],
            options={
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='証書番号')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued', to='members.certificate')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='contacts.contact')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='members.enrollment')),
            ],
            options={
                'db_table': 'issued_certificates',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='選択肢テキスト')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='members.question')),
            ],
            options={
                'db_table': 'quiz_choices',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='テスト説明')),
                ('passing_score', models.IntegerField(default=70, verbose_name='合格ライン(%)')),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True, verbose_name='制限時間(分)')),
                ('max_attempts', models.IntegerField(default=0, help_text='0=無制限', verbose_name='最大受験回数')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='問題順ランダム')),
                ('shuffle_choices', models.BooleanField(default=False, verbose_name='選択肢ランダム')),
                ('is_gate', models.BooleanField(default=False, help_text='合格しないと次のレッスンに進めない', verbose_name='ゲート')),
                ('is_final_test', models.BooleanField(default=False, help_text='合格で卒業証書を発行', verbose_name='最終テスト')),
                ('show_correct_answers', models.BooleanField(default=True, verbose_name='正解を表示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='members.lesson')),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='members.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='得点')),
                ('max_score', models.IntegerField(default=0, verbose_name='満点')),
                ('percentage', models.IntegerField(default=0, verbose_name='正解率(%)')),
                ('passed', models.BooleanField(default=False, verbose_name='合格')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='members.enrollment')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='members.quiz')),
            ],
            options={
                'db_table': 'quiz_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.question')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='quiz_answers', to='members.choice')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='members.quizattempt')),
            ],
            options={
                'db_table': 'quiz_answers',
            },
        ),
    ]
