# Generated by Django 5.2.11 on 2026-03-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='can_manage_bookings',
            field=models.BooleanField(default=True, verbose_name='予約管理'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_manage_contacts',
            field=models.BooleanField(default=True, verbose_name='コンタクト管理'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_manage_emails',
            field=models.BooleanField(default=True, verbose_name='メール配信管理'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_manage_funnels',
            field=models.BooleanField(default=True, verbose_name='ファネル管理'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_manage_members',
            field=models.BooleanField(default=True, verbose_name='会員サイト管理'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_manage_products',
            field=models.BooleanField(default=True, verbose_name='商品管理'),
        ),
    ]
