# Generated by Django 5.2.11 on 2026-03-04 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_add_operator_permissions'),
        ('contacts', '0001_initial'),
        ('members', '0003_question_course_prerequisite_quiz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('body', models.TextField(verbose_name='内容')),
                ('status', models.CharField(choices=[('open', '未対応'), ('replied', '返信済み'), ('closed', 'クローズ')], default='open', max_length=20, verbose_name='ステータス')),
                ('admin_reply', models.TextField(blank=True, verbose_name='管理者返信')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='返信日時')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='contacts.contact')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='members.membersite')),
            ],
            options={
                'db_table': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, verbose_name='セッションキー')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='ユーザーエージェント')),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_sessions', to='contacts.contact')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_sessions', to='members.membersite')),
            ],
            options={
                'db_table': 'member_sessions',
                'ordering': ['-logged_in_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('status', models.CharField(choices=[('open', 'オープン'), ('pending', '対応待ち'), ('closed', 'クローズ')], default='open', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_threads', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to='accounts.project')),
            ],
            options={
                'db_table': 'support_threads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='本文')),
                ('is_from_admin', models.BooleanField(default=False, verbose_name='システム管理者から')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='既読日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sysadmin.supportthread')),
            ],
            options={
                'db_table': 'support_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
