# Generated by Django 5.2.11 on 2026-03-04 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='予約タイプ名')),
                ('slug', models.SlugField(verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='所要時間(分)')),
                ('location_type', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('phone', '電話'), ('in_person', '対面')], default='zoom', max_length=20, verbose_name='場所タイプ')),
                ('location_detail', models.CharField(blank=True, max_length=500, verbose_name='場所詳細')),
                ('buffer_before_minutes', models.IntegerField(default=0, verbose_name='前バッファ(分)')),
                ('buffer_after_minutes', models.IntegerField(default=10, verbose_name='後バッファ(分)')),
                ('max_bookings_per_day', models.IntegerField(default=0, help_text='0=無制限', verbose_name='1日の最大予約数')),
                ('confirmation_subject', models.CharField(blank=True, default='ご予約が確定しました', max_length=200, verbose_name='確認メール件名')),
                ('confirmation_body', models.TextField(blank=True, default='ご予約ありがとうございます。\n\n日時: {date} {time}\n所要時間: {duration}分', verbose_name='確認メール本文')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('add_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.tag', verbose_name='タグ付与')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_types', to='accounts.project')),
                ('start_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.scenario', verbose_name='シナリオ開始')),
            ],
            options={
                'db_table': 'booking_types',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='BookingAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], verbose_name='曜日')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('booking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='bookings.bookingtype')),
            ],
            options={
                'db_table': 'booking_availabilities',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='開始日時')),
                ('end_datetime', models.DateTimeField(verbose_name='終了日時')),
                ('status', models.CharField(choices=[('confirmed', '確定'), ('cancelled', 'キャンセル'), ('completed', '完了'), ('no_show', 'ノーショー')], default='confirmed', max_length=20, verbose_name='ステータス')),
                ('google_event_id', models.CharField(blank=True, max_length=200, verbose_name='GoogleカレンダーイベントID')),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=200, verbose_name='ZoomミーティングID')),
                ('zoom_join_url', models.CharField(blank=True, max_length=500, verbose_name='Zoom参加URL')),
                ('zoom_start_url', models.CharField(blank=True, max_length=500, verbose_name='ZoomホストURL')),
                ('guest_memo', models.TextField(blank=True, verbose_name='ゲストメモ')),
                ('admin_memo', models.TextField(blank=True, verbose_name='管理者メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='キャンセル日時')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='contacts.contact')),
                ('booking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.bookingtype')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials_json', models.TextField(blank=True, verbose_name='認証情報(JSON)')),
                ('calendar_id', models.CharField(default='primary', max_length=200, verbose_name='カレンダーID')),
                ('is_active', models.BooleanField(default=False, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_integration', to='accounts.project')),
            ],
            options={
                'db_table': 'calendar_integrations',
            },
        ),
        migrations.CreateModel(
            name='ZoomIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, max_length=200, verbose_name='アカウントID')),
                ('client_id', models.CharField(blank=True, max_length=200, verbose_name='クライアントID')),
                ('client_secret', models.CharField(blank=True, max_length=200, verbose_name='クライアントシークレット')),
                ('is_active', models.BooleanField(default=False, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_integration', to='accounts.project')),
            ],
            options={
                'db_table': 'zoom_integrations',
            },
        ),
        migrations.CreateModel(
            name='BookingBlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='ブロック日')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='理由')),
                ('booking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='bookings.bookingtype')),
            ],
            options={
                'db_table': 'booking_blocked_dates',
                'ordering': ['date'],
                'unique_together': {('booking_type', 'date')},
            },
        ),
    ]
