# Generated by Django 5.2.11 on 2026-03-03 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ファネル名')),
                ('slug', models.SlugField(verbose_name='スラッグ')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnels', to='accounts.project')),
            ],
            options={
                'db_table': 'funnels',
                'unique_together': {('project', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='FunnelPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ページタイトル')),
                ('slug', models.SlugField(verbose_name='スラッグ')),
                ('page_type', models.CharField(choices=[('lp', 'ランディングページ'), ('thanks', 'サンクスページ'), ('sales', 'セールスページ'), ('form', 'フォームページ'), ('upsell', 'アップセルページ')], default='lp', max_length=20, verbose_name='ページタイプ')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='メタタイトル')),
                ('meta_description', models.TextField(blank=True, verbose_name='メタディスクリプション')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='funnels.funnel')),
            ],
            options={
                'db_table': 'funnel_pages',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'ヒーローセクション'), ('text', 'テキスト'), ('image', '画像'), ('video', '動画埋め込み'), ('button', 'CTAボタン'), ('form', 'フォーム'), ('countdown', 'カウントダウン'), ('testimonial', 'お客様の声'), ('faq', 'FAQ'), ('separator', '区切り線')], max_length=20, verbose_name='セクションタイプ')),
                ('content', models.JSONField(default=dict, verbose_name='コンテンツ')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_visible', models.BooleanField(default=True, verbose_name='表示')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='funnels.funnelpage')),
            ],
            options={
                'db_table': 'page_sections',
                'ordering': ['sort_order'],
            },
        ),
    ]
