# Generated by Django 5.2.11 on 2026-03-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'ヒーローセクション'), ('text', 'テキスト'), ('image', '画像'), ('video', '動画埋め込み'), ('button', 'CTAボタン'), ('form', 'フォーム'), ('countdown', 'カウントダウン'), ('testimonial', 'お客様の声'), ('faq', 'FAQ'), ('schedule', 'スケジュール予約'), ('meeting', 'ミーティング予約'), ('separator', '区切り線')], max_length=20, verbose_name='セクションタイプ'),
        ),
    ]
