# Generated by Django 5.2.11 on 2026-03-10 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0002_add_schedule_meeting_section_types'),
        ('members', '0003_question_course_prerequisite_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnel',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnels', to='members.membersite', verbose_name='会員サイト'),
        ),
    ]
