# Generated by Django 5.2.11 on 2026-03-03 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='キャンペーン名')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('body_html', models.TextField(verbose_name='本文(HTML)')),
                ('body_text', models.TextField(blank=True, verbose_name='本文(テキスト)')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('scheduled', '予約済み'), ('sending', '送信中'), ('sent', '送信済み')], default='draft', max_length=20, verbose_name='ステータス')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='配信予定日時')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='配信日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.project')),
                ('target_tags', models.ManyToManyField(blank=True, to='contacts.tag', verbose_name='ターゲットタグ')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='シナリオ名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='accounts.project')),
            ],
            options={
                'db_table': 'scenarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='ステップ番号')),
                ('delay_days', models.IntegerField(default=0, verbose_name='遅延日数')),
                ('delay_hours', models.IntegerField(default=0, verbose_name='遅延時間')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('body_html', models.TextField(verbose_name='本文(HTML)')),
                ('body_text', models.TextField(blank=True, verbose_name='本文(テキスト)')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='emails.scenario')),
            ],
            options={
                'db_table': 'scenario_steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('email_type', models.CharField(choices=[('scenario', 'シナリオ'), ('campaign', '一斉配信')], max_length=20, verbose_name='種別')),
                ('status', models.CharField(choices=[('sent', '送信済'), ('failed', '失敗'), ('opened', '開封'), ('clicked', 'クリック')], default='sent', max_length=20, verbose_name='ステータス')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='contacts.contact')),
                ('scenario_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.scenariostep')),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('current_step', models.IntegerField(default=0, verbose_name='現在のステップ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_subscriptions', to='contacts.contact')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='emails.scenario')),
            ],
            options={
                'db_table': 'scenario_subscriptions',
                'unique_together': {('scenario', 'contact')},
            },
        ),
    ]
