# Generated by Django 5.2.11 on 2026-03-10 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('members', '0003_question_course_prerequisite_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='members.membersite', verbose_name='会員サイト'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='members.membersite', verbose_name='会員サイト'),
        ),
    ]
