# Generated by Django 5.2.11 on 2026-03-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_add_site_to_scenario_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='cta_url',
            field=models.URLField(blank=True, help_text='メール本文内の{{cta_url}}に置換されます', verbose_name='申込リンクURL'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='sender_name',
            field=models.CharField(blank=True, help_text='メール本文内の{{sender_name}}に置換されます', max_length=200, verbose_name='運営者名（差出人名）'),
        ),
    ]
